def get_help_text():
    return (
        "📚 *CEX PRO COMMAND LIST*\n"
        "━━━━━━━━━━━━━━━━\n\n"
        "🟢 *GETTING STARTED*\n"
        "• `menu`, `hi`, `start` : Show the main dashboard\n"
        "• `help` : Show this help menu\n"
        "• `balance`, `wallet` : View Crypto & Fiat funds\n"
        "• `deposit [COIN] [CHAIN]` : Get your crypto wallet address (Ex: `deposit BTC BTC`, `deposit USDT TRC20`)\n"
        "• `deposit methods` : List all supported off-chain deposit methods\n"
        "• `deposit [METHOD]` : Get details for PayPal, CashApp, Venmo, Zelle, or Bank\n"
        "\n"
        "📈 *MARKET DATA*\n"
        "• `price [COIN]` : Check live price (Ex: `price SOL`)\n"
        "• `top gainers` : See today's best performers\n"
        "\n"
        "🔔 *ALERTS*\n"
        "• `alert [COIN] [PRICE]` : Set price alarm (Ex: `alert BTC 100000`)\n"
        "• `alerts` : View your active alarms\n"
        "\n"
        "💱 *OTC & FIAT (CASH)*\n"
        "• `otc`, `p2p` : View today's Exchange Rates\n"
        "• `swap [FROM] [TO] [AMT]` : Instant conversion\n"
        "  _(Ex: `swap BTC NGN 0.1`, `swap USDT NGN 50`)_\n"
        "\n"
        "🏦 *WITHDRAWALS*\n"
        "• `withdraw [COIN] [AMT] [ADDR]` : Send Crypto out\n"
        "  _(Ex: `withdraw BTC 0.01 bc1...`, `withdraw USDT 100 T9y...`)_\n"
        "• `withdraw [FIAT] [AMT] [BANK]` : Cash out to Bank\n"
        "  _(Ex: `withdraw NGN 50000 1234567890 Access_Bank`)_\n"
        "\n"
        "💸 *INTERNAL TRANSFER*\n"
        "• `transfer [COIN] [AMOUNT] [TO_PHONE]` : Send assets to another user\n"
        "  _(Ex: `transfer USDT 10 +2348012345678`)_\n"
        "\n"
        "📝 *HISTORY*\n"
        "• `history`, `transactions` : View last 5 transactions\n"
        "\n"
        "❓ *SUPPORT*\n"
        "• `support` : Get admin contact details\n"
        "• `support [Your Message]` : Open a support ticket\n"
        "• `tickets`, `ticket` : View your support tickets\n"
        "• `security`, `freeze`, `2fa`, `report` : Security center options\n"

        "\n💡 *VTU & Bill Payments*\n"
        "• `airtime [network] [phone] [amount]` : Buy airtime (e.g. `airtime mtn 08012345678 500`)\n"
        "• `data [network] [phone] [plan_id]` : Buy data bundle (e.g. `data mtn 08012345678 2682`)\n"
        "• `electricity [disco] [meter] [type] [amount]` : Pay electricity bill (e.g. `electricity ikeja-electric 12345678901 prepaid 1000`)\n"
        "• `tv [provider] [card] [plan_id]` : Pay TV subscription (e.g. `tv dstv 1234567890 2701`)\n"
        "• `epins [network] [value] [qty]` : Buy recharge card pins (e.g. `epins mtn 500 2`)\n"
        "• `betting [provider] [account] [amount]` : Fund betting account (e.g. `betting Bet9ja 12345 500`)\n"

        "\n💳 *Payment Methods*\n"
        "• `deposit methods` : List all supported off-chain deposit methods\n"
        "• `deposit [METHOD]` : Get details for PayPal, CashApp, Venmo, Zelle, or Bank\n"
    )

def get_admin_help():
    """
    Only visible to YOU.
    """
    return (
        "🕵️ *ADMIN COMMANDS*\n"
        "━━━━━━━━━━━━━━━━\n"
        "• `admin` : This menu\n"
        "• `users` : List all registered users\n"
        "• `withdrawals` : View pending payout requests\n"
        "• `approve [ID] [HASH]` : Mark withdrawal as DONE\n"
        "• `broadcast [MSG]` : Send message to ALL users"
    )